### ISSUE TITLE
motions文件夹为空

### ISSUE THREAD

**Issue by jiaoxiaohang** [zwa73/UnityLive2DExtractor-Unofficial#1]
提取后motion文件夹为空,其他文件都没问题,为什么提取不了动作文件呢,是加密了吗?
![image](https://github.com/zwa73/UnityLive2DExtractor-Unofficial/assets/69664925/48779e85-34d4-4f37-8c4b-3a800c8779e9)

**Comment by jiaoxiaohang** [comment]
这是源文件
[Uploading 2a5eed27f390a53be1571b95af588a5b.zip…]()

**Comment by zwa73** [comment]
说明mtn不在理想位置，用AssetStudio解包找动作文件即可，一般在同位置

**Comment by jiaoxiaohang** [comment]
> 说明mtn不在理想位置，用AssetStudio解包找动作文件即可，一般在同位置

我在AssetStudio对上面这个文件解包,确定有动作文件,但放到[UnityLive2DExtractor提取出来motions却是空的

**Comment by jiaoxiaohang** [comment]
在AssetStudio对文件右键"输出选定资产"也提取不出来
![image](https://github.com/zwa73/UnityLive2DExtractor-Unofficial/assets/69664925/b8e81dbb-ff04-4d28-bf62-4627a71481ab)

**Comment by zwa73** [comment]
首先确定是在用最新版本的astudio
.net6版本可能会有些问题，可以尝试换.net472版本
如果还是无法提取那可能是只输入了资源表但是缺少resS(资源数据文件)，可以尝试拖曳更完整的文件夹
再不行建议直接去AssetStudio那发issue，毕竟这个东西主要是依赖于AssetStudio

**Comment by jiaoxiaohang** [comment]
我了解到AssetStudio无法导出AnimationClip,准备放弃了/(ㄒoㄒ)/~~
