### ISSUE TITLE
提取得到的moc3文件无法使用

### ISSUE THREAD

**Issue by Xyloces-Zoot** [zwa73/UnityLive2DExtractor-Unofficial#5]
首先十分感谢这个项目解决了很多问题。但是提取某一个项目时，得到的moc3文件在导入时提示无法使用，能否请帮忙看看是什么问题、并有无解决的可能？十分感谢！(._. )>
附上源文件和得到的资源链接：https://www.123865.com/s/cZoSTd-xP7Xv

**Comment by zwa73** [comment]
看了下hex结构没啥明显问题，试了一下其他提取方式也一样无法直接打开，没办法帮你

**Comment by Xyloces-Zoot** [comment]
> 看了下hex结构没啥明显问题，试了一下其他提取方式也一样无法直接打开，没办法帮你

好的谢谢哦 (。﹏ 。*)

**Comment by Xyloces-Zoot** [comment]
> 看了下hex结构没啥明显问题，试了一下其他提取方式也一样无法直接打开，没办法帮你

重新思考了一下，发现提取出来的texture是从01开始编号的，于是又做了一个一样的空白贴图，一起勾选导入就可以使用了。
虽然不知道什么原理，那么提取的moc3文件就是正常的；项目很好用，好评 ( •̀ ω •́ )y ★
